name: daniknews
description: unbaised short video neutral news app.
publish_to: 'none'

version: 1.0.11+12

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.2.1
  google_fonts:

  url_launcher: ^6.0.13
  image_picker: ^1.0.7
  video_player: ^2.2.7
  path_provider: ^2.0.7

  path: ^1.8.0
  sqflite: ^2.0.0+4
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
